name: Single docker image push to HuaweiCloud

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      image:
        description: 'image_name:tag'
        required: true
        default: ''

env:
  HWC_REGISTRY: "${{ vars.HWC_REGISTRY }}"
  HWC_SWR_PROJECT: "${{ secrets.HWC_SWR_PROJECT }}"
  HWC_REGISTRY_USER: "${{ secrets.HWC_REGISTRY_USER }}"
  HWC_REGISTRY_PASSWORD: "${{ secrets.HWC_REGISTRY_PASSWORD }}"
  HWC_AK: "${{ secrets.HWC_AK }}"
  HWC_SK: "${{ secrets.HWC_SK }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        # remove-android: 'true'
        # remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image to HuaweiCloud
      run: |
        docker login -u $HWC_REGISTRY_USER -p $HWC_REGISTRY_PASSWORD $HWC_REGISTRY
        # 数据预处理,判断镜像是否重名
        origin_image=${{github.event.inputs.image}}
        # 将@sha256:等字符删除
        full_image="${origin_image%%@*}"
        echo "=============================================================================="
        echo "full_image: $full_image"
        # 获取镜像名:版本号  例如 1panel/kubepi:latest
        image_name_with_tag=$(echo "$full_image" | awk -F'/' '{print $NF}')
        # 如kubepi:latest
        echo "image_name_with_tag: $image_name_with_tag"
        # 获取命名空间 例如kasmweb,  这里有种特殊情况 docker.io/nginx，把docker.io当成命名空间，也OK
        name_space=$(echo "$image" | awk -F'/' '{if (NF==3) print $2; else if (NF==2) print $1; else print ""}')
        echo "name_space: $name_space"
        # 获取镜像名例如kubepi
        image_name=$(echo "$image_name_with_tag" | awk -F':' '{print $1}')
        echo "image_name: $image_name"
        repository=$(echo "$full_image" | awk -F':' '{print $1}')
        echo "swr repository: $repository"
        # 1panel/kubepi
        echo "SWR_REPOSITORY=$HWC_SWR_PROJECT/$repository" >> $GITHUB_ENV
        echo "docker pull $full_image"
        docker pull $full_image
        new_image="$HWC_REGISTRY/$HWC_SWR_PROJECT/$full_image"
        echo "docker tag $full_image $new_image"
        docker tag $full_image $new_image
        echo "docker push $new_image"
        docker push $new_image
        echo "开始清理磁盘空间"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
        docker rmi $full_image
        docker rmi $new_image
        echo "磁盘空间清理完毕"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="
    - name: Set HuaweiCloud repo to public
      run: |
        echo "start to set the image to public"
        curl -sSL https://cn-north-4-hdn-koocli.obs.cn-north-4.myhuaweicloud.com/cli/latest/hcloud_install.sh | bash
        hcloud SWR UpdateRepo --access-key="$HWC_AK" --secret-key="$HWC_SK"  --X-Language="zh-cn" --project_id="e5c8272994c0490fa199baec4c058d47" --Content-Type="application/json" --namespace="$HWC_SWR_PROJECT" --repository="$SWR_REPOSITORY" --is_public=true

